version: "3.8"

services:
    nginx:
        container_name: nginx
        image: nginx:stable
        depends_on:
            - rpcnode
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ${CERT_FULLCHAIN}:/etc/ssl/certs/${DOMAIN}/fullchain.pem:ro
            - ${CERT_PRIVKEY}:/etc/ssl/certs/${DOMAIN}/privkey.pem:ro
        networks:
            - default
            - geth-net
        restart: unless-stopped

networks:
    geth-net:
        driver: bridge
        ipam:
            config:
                - subnet: "172.172.172.0/28"
                  gateway: "172.172.172.1"
