version: "3.8"

services:
    nginx:
        container_name: nginx
        image: nginx:stable
        depends_on:
            - rpcnode
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./http.conf:/etc/nginx/conf.d/http.conf:ro
            - ./stream.conf:/etc/nginx/conf.d/stream.conf:ro
        networks:
            - default
            - geth-net
        restart: unless-stopped

networks:
    geth-net:
        driver: bridge
        ipam:
            config:
                - subnet: "172.172.172.0/28"
                  gateway: "172.172.172.1"
