version: "3.8"

services:
    nginx:
        volumes:
            - ${APPLICATION_PATH}/dist:/var/www:ro
    node-app:
      container_name: node-app
      build: ./node-app
      ports:
        - "3000:3000"
      networks:
        - default