version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 9090:9090
      - "30808:30808/udp"
      - "30808:30808/tcp"
    volumes:
      - ${HOST_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${HOST_DIR}/http.conf:/etc/nginx/conf.d/http.conf:ro
      - ${HOST_DIR}/stream.conf:/etc/nginx/conf.d/stream.conf:ro
    networks:
      - default
      - geth-net
    restart: unless-stopped

networks:
  geth-net:
    ipam:
      config:
        - subnet: "172.172.172.0/28"
          ip_range: "172.172.172.0/28"
