version: "3.8"

services:
  nginx:
    depends_on:
      - rpcnode
  rpcnode:
    container_name: rpcnode
    image: gethnode:latest
    command: [
      "--networkid", "${CHAIN_ID}",
      "--datadir", "/.ethereum",
      "--http",
      "--http.api", "eth,net,rpc,web3,txpool",
      "--http.addr", "0.0.0.0",
      "--http.vhosts", "*",
      "--http.corsdomain", "https://${DOMAIN}",
      "--bootnodes", "enode://${BOOTNODE_ENODE}@172.172.172.2:30303",
      "--netrestrict", "172.172.172.0/28,192.168.86.0/24",
      "--nat", "extip:172.172.172.2",
      "--syncmode", "full",
      "--gcmode", "archive",
      "--txpool.lifetime", "12s",
      "--txpool.pricebump", "1",
      "--nodekey", "bootnode.key"
    ]
    volumes:
      - ${CHAIN_DIR}/rpc/.ethereum/:/.ethereum/
      - ${CHAIN_DIR}/genesis.json:/genesis.json
      - ${CHAIN_DIR}/bootnode.key:/bootnode.key
    expose:
      - 8545
      - "30303/tcp"
      - "30303/udp"
    networks:
      geth-net:
        ipv4_address: 172.172.172.2
    restart: unless-stopped
