version: "3.8"

services:
  sealingnode:
    container_name: sealingnode
    image: gethnode:latest
    command: [
      "--unlock", "${SEALER_ACCOUNT}",
      "--password", "password.txt",
      "--mine",
      "--networkid", "${CHAIN_ID}",
      "--datadir", "/.ethereum",
      "--bootnodes", "enode://${BOOTNODE_ENODE}@172.172.172.2:30303",
      "--netrestrict", "172.172.172.0/28",
      "--nat", "extip:172.172.172.3",
      "--ipcdisable",
      "--syncmode", "full",
      "--gcmode", "archive",
      "--txpool.lifetime", "12s",
      "--txpool.pricebump", "1",
      "--ignore-legacy-receipts"
    ]
    volumes:
      - ${CHAIN_DIR}/sealer/.ethereum/:/.ethereum/
      - ${CHAIN_DIR}/genesis.json:/genesis.json
      - ${CHAIN_DIR}/password.txt:/password.txt
    networks:
      geth-net:
        ipv4_address: 172.172.172.3
    restart: unless-stopped
